### ISSUE TITLE
Meta-geom: Make a single stat_slabinterval / geom_slabinterval from the hacked violins/densities, pointinterval, and eye geoms

### ISSUE THREAD

**Issue by mjskay** [mjskay/tidybayes#84]
TODOs:

- [x] add a few more shortcuts (and update the family overview image):
  - [x] `stat_dist_interval[h]`
  - [x] `stat_dist_pointinterval[h]`
  - [x] `stat_slab[h]`
  - [x] `stat_dist_slab[h]`
  - [x] `geom_slab[h]` ?
- [x] tests please: 
  - [x] break functions out so can see coverage
  - [x] tests for scale transformations in stats with things like scale_x_log10()
- [x] add examples to new geom docs (search for TODO). Can pull from slabinterval vignette. Then point people in the vignette direction from the examples
- [x] output n so people can use n*density if desired
- [x] add a few more of the specific aesthetics (plus test):
  - [x] point_alpha
  - [x] interval_alpha
  - [x] slab_fill
  - [x] slab_alpha
- [x] reference in README, other vignettes (even if just pointing to slabinterval vignette)
- [x] document aesthetics for geom_slabinterval and sub-geoms
- [x] change old geom_[half]eye[h] refs to stat_[half]eye[h]
- [x] speed up gradient by using polygon directly for groups
- [x] make thickness a different stat
- [x] build cool new stuff the meta-geom makes easy:
  - [x] CCDF bar charts
  - [x] stats for analytical distributions, e.g. priors; both densities and CDFs
  - [x] gradient plots
  - [x] histograms (see #162)
- [x] build ridiculous meta-geom
- [x] decide on good name
- [x] implement a key / legend drawing function
  - [x] remove old draw_key funcs
- [x] look into dropping ggstance stuff in docs (except dodgev)
- [x] document use of position dodge
- [x] reimplement base geoms (not stats) on meta-geom
- [x] undo weird interval_size scale and revert to fatten / etc
- [x] fix existing stats
- [x] build generic meta-stat (and make it faster)
  - [x] rebuild stat_pointinterval and stat_interval on top of this
- [x] add in depracted argument alias for relative_scale -> scale
- [x] fix behavior of `position_dodge` for pointintervals / eyes / halfeyes (it now works for intervals, see #180)
- [x] Make sure aesthetics for different parts of the geom are exposed (fill, alpha, outline, etc)
- [x] make sure defaults only work when corresponding column exists; see failure of geom_pointinterval in readme and make a test.

**Comment by mjskay** [comment]
Could also merge all this with pointinterval and make a geom_density_interval or something (in any case that's a better name), but keep all the aliases.

**Comment by mjskay** [comment]
Done for now --- everything else relevant has been split into other issues
