### ISSUE TITLE
Decide what (if anything else) to do to help with stan_polr fits in add_fitted_samples

### ISSUE THREAD

**Issue by mjskay** [mjskay/tidybayes#87]
Stemming from #85 comes the realization that while brms gives predicted probabilities (or log odds) for each category in ordinal models, rstanarm just gives the predicted latent variable, leaving it to the user to derive category-specific estimates if desired.

It might be nice for the output to be comparable across these. Some possible approaches:

1. Leave it as-is. This is the "defer to packages/model types, just tidy whatever they give us" approach in terms of output format philosophy, and is the current approach.

2. Transform it into a comparable form to brms. This is a somewhat opinionated and heavy-handed approach, and possibly also a difficult to maintain one --- this basically involves committing to keeping track of all the possible ordinal and multinomial models in the packages that tidybayes supports now and in the future, figuring out enough of their APIs and internals to do these transformations, ensuring correctness, etc.

3. Provide an option to do this transformation. This doesn't really solve the support problem of (2). Maybe this is ultimately the best approach, but if implemented would probably have to wait until post-CRAN.

4. Provide an example in the rstanarm vignette and code for some other way to easily transform the rstanarm output into brms-like output *after* add_fitted_samples has been run, e.g. using existing tidyverse functions + tidybayes (possibly creating a new function if necessary). This puts a little more burden on users, but may avoid more heavyweight support.

**TODOs**:

- [x] make the docs for add_[fitted|predicted]_samples clear that the current approach is (1), and that model output may be slightly different between packages (with ordinal as an example).
- [x] add examples to the vignettes illustrating this difference, plus an example to make stan_polr output probabilities.
    - [x] add example to brms vignette
    - [x] add example to rstanarm vignette
- [x] see if the approach to doing this in the vignette can be improved using the new support for arrays in gather/spread_draws (I think it might be...)

**Comment by tmastny** [comment]
To add some context to this issue, it seems there is a fundamental philosophical difference between `brms` and `rstanarm`. 

The documentation of `rstanarm` sort of disowns `posterior_linpred`: "This function is occasionally useful, but it should be used sparingly." 
[http://mc-stan.org/rstanarm/reference/posterior_linpred.stanreg.html](url)

Moreover, one of the developers argued that "[t]hose probabilities are not all that useful," with regards to ordinal models.
[http://discourse.mc-stan.org/t/posterior-linpred-with-ordinal-models/2260/6](url)

Whereas the `brms` method `fitted` provides detailed probability sampling from the model, as seen in issue #85. 

To me, this says two things.

1. Maybe those sort of probabilities are overrated. The `rstanarm` team are experienced developers and statisticians, so I'm sure they have a reason even if it isn't clear to me. Based on the logistic regression posterior predictive check on page 154 in Bayesian Data Analysis 3rd edition, I can see the case where the regression probabilities align with the data, but the generative model is all wrong. So in some sense you might be throwing away information by just looking at probabilities. I think I see the utility in this, but at some point I have to imagine you want to answer the question "what is the probability someone with these characteristics will choose X?" and `rstanarm` doesn't have a nice way to answer that. It would be nice to be able to get those answers without a lot of work and maybe tidybayes could help.

2. I think there is a combination of 1 and 4 that would be really helpful, and could be implemented easily and immediately. Let users know there are differences between `brms` and `rstanarm` and so they can make an informed choice. Right now the documentation makes it seem as `add_[fitted/predicted]_samples` should produce the same results, but we now know that isn't the case. I think simply letting users know that the results depend on both the model and package will go a long way. Especially since documentation for both `brms` and `rstanarm` isn't well developed enough yet to make these things super clear.

I'm not sure exactly sure what to make of all this, but I do think it is worthwhile to consider the various options and I'm glad you opened the issue.

**Comment by mjskay** [comment]
Ah yeah, your second point is a very good one. The docs should at least be transparent about the differences, and providing an example wouldn't be hard to do in the vignettes pre-CRAN.

**Comment by mjskay** [comment]
@tmastny I've taken a pass at the pre-CRAN edits for this. Specifically, I've added a parallel example of fitting the same ordinal model (modulo priors) in brms and rstanarm:

http://mjskay.github.io/tidybayes/articles/tidy-brms.html#ordinal-model-with-categorical-predictor

http://mjskay.github.io/tidybayes/articles/tidy-rstanarm.html#ordinal-model-with-categorical-predictor

The latter includes the derivation to get predicted probabilities within each category.

I've also added a note on the documentation of the `category` argument to `add_fitted_samples` mentioning that not all ordinal models may use it:

http://mjskay.github.io/tidybayes/reference/add_predicted_samples.html

I am punting anything else on this issue until after a CRAN submission (and leaving it open to gather any such thoughts). Any feedback/suggestions on the above changes would be appreciated!

**Comment by tmastny** [comment]
Wow, the website looks great! I had no idea about `compare_levels`, I look forward to playing with that. I'll have some time to look into the categorical models and give some feedback soon. Great work!

**Comment by mjskay** [comment]
This looks all mostly resolved now --- there's code in the vignettes showing how to do the thresholds and whatnot. Array support in gather/spread draws turned out not to help here because of how the parameters are named, so I am closing this as I think it's as good as it'll get for now.
